-- SQLite
CREATE TABLE SENSORS(
ID          INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
USER        CHAR(20),
PLACE       CHAR(20),
SENSOR      CHAR(20),
VALUE       REAL,
REG_DATE    DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE SENSORS